version: "3.8"

services:
  postgres-product:
    image: postgres:16
    container_name: postgres_product
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata_product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-inventory:
    image: postgres:16
    container_name: postgres_inventory
    environment:
      POSTGRES_DB: inventory_items_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata_inventory:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_items_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    container_name: product_service
    build:
      context: ../backend/product-service
      dockerfile: Dockerfile_backup
    depends_on:
      postgres-product:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-product:5432/product_db
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_pass

  inventory-service:
    container_name: inventory_service
    build:
      context: ../backend/inventory-service
      dockerfile: Dockerfile_backup
    depends_on:
      postgres-inventory:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inventory:5432/inventory_items_db
      SPRING_DATASOURCE_USERNAME: inventory_user
      SPRING_DATASOURCE_PASSWORD: inventory_pass

volumes:
  pgdata_product:
  pgdata_inventory: